qiskit-community/povm-toolbox

- povm_toolbox/library/classical_shadows.py
- povm_toolbox/library/locally_biased_classical_shadows.py
- povm_toolbox/library/randomized_projective_measurements.py
- pyproject.toml
- test/library/test_randomized_projective_measurements.py
> Add built-in measurement twirling

- docs/how_tos/job_recovery.ipynb
- povm_toolbox/sampler/povm_sampler_job.py
- test/sampler/test_povm_sampler_job.py
> Job recovery with pickled metadata

- test/post_processor/test_post_processor.py
- test/sampler/test_povm_sampler_job.py
> Complete  the unittests for the `POVMPostProcessor` class

- test/post_processor/test_dual_from_empirical_frequencies.py
- test/post_processor/test_dual_from_marginal_probabilities.py
- test/post_processor/test_dual_from_state.py
Follow-up PR to #41 and #42, complete the test updates for the `post_processor` module.
> Update unittests of `post_processor` module

- test/sampler/test_povm_sampler_result.py
> Unittests for `POVMPubResult`

- povm_toolbox/library/mutually_unbiased_bases_measurements.py
- test/library/test_mutually_unbiased_bases_measurements.py
> Complete the unittests for the `MutuallyUnbiasedBasesMeasurements` class

- test/library/test_locally_biased_classical_shadows.py
> Complete the unittests for the `LocallyBiasedClassicalShadows` class

- test/library/test_classical_shadows.py
> Complete the unittests for the `ClassicalShadows` class

- test/test_utilities.py
> Complete the unittests for the utilities functions

- povm_toolbox/library/randomized_projective_measurements.py
- test/library/test_randomized_projective_measurements.py
> Complete the unittests for the `RandomizedProjectiveMeasurements` class

- povm_toolbox/post_processor/__init__.py
- povm_toolbox/post_processor/dual_from_empirical_frequencies.py
- povm_toolbox/post_processor/dual_from_marginal_probabilities.py
- povm_toolbox/post_processor/dual_from_state.py
- povm_toolbox/post_processor/povm_post_processor.py
> [docs] Cleanup of the `post_processor` documentation

- povm_toolbox/quantum_info/multi_qubit_frame.py
- test/quantum_info/test_multi_qubit_dual.py
- test/quantum_info/test_multi_qubit_povm.py
- test/quantum_info/test_single_qubit_povm.py
> Complete unittests for `MultiQubitFrame`, `MultiQubitFramePOVM` and `MultiQubitFrameDual` classes

- povm_toolbox/quantum_info/product_frame.py
- test/quantum_info/test_product_dual.py
- test/quantum_info/test_product_povm.py
> Complete unittests for `ProductFrame`, `ProductPOVM` and `ProductDual` classes

- .mergify.yml
Mergify will allow us to automate the backporting of PRs.
> ci: set up mergify

- pyproject.toml
Note that this can only merge into `stable/0.1`
> Release 0.1.1

- pyproject.toml
- releasenotes/notes/qiskit-2.0-3f61e61cfb2b222d.yaml
Updates the maximum supported Qiskit version.
We know that this version is already supported since our development tests in CI are passing :+1:
> Support Qiskit 2.0

- pyproject.toml
See also [1].
[1]: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license-and-license-files
> Update license specification inline with PEP 639

- povm_toolbox/library/dilation_measurement.py
- povm_toolbox/library/locally_biased_classical_shadows.py
- povm_toolbox/library/mutually_unbiased_bases_measurements.py
- povm_toolbox/library/randomized_projective_measurements.py
- test/library/test_dilation_measurements.py
- test/library/test_locally_biased_classical_shadows.py
- test/library/test_mutually_unbiased_bases_measurements.py
- test/library/test_randomized_projective_measurements.py
> Allow array-like arguments

- pyproject.toml
- test/library/metadata/test_povm_metadata.py
- test/library/metadata/test_rpm_metadata.py
- test/library/test_classical_shadows.py
- test/library/test_dilation_measurements.py
- test/library/test_locally_biased_classical_shadows.py
- test/library/test_mutually_unbiased_bases_measurements.py
- test/library/test_povm_implementation.py
- test/library/test_randomized_projective_measurements.py
- test/post_processor/test_dual_from_empirical_frequencies.py
- test/post_processor/test_dual_from_marginal_probabilities.py
- test/post_processor/test_dual_from_state.py
- test/post_processor/test_median_of_means.py
- test/post_processor/test_post_processor.py
- test/quantum_info/test_multi_qubit_dual.py
- test/quantum_info/test_multi_qubit_frame.py
- test/quantum_info/test_multi_qubit_povm.py
- test/quantum_info/test_product_dual.py
- test/quantum_info/test_product_frame.py
- test/quantum_info/test_product_povm.py
- test/quantum_info/test_single_qubit_povm.py
- test/sampler/test_povm_pub_result.py
- test/sampler/test_povm_sampler.py
- test/sampler/test_povm_sampler_job.py
- test/sampler/test_povm_sampler_pub.py
- test/test_utilities.py
> Replace unittest with pytest

- povm_toolbox/library/povm_implementation.py
- povm_toolbox/sampler/povm_pub_result.py
- test/library/test_classical_shadows.py
- test/library/test_dilation_measurements.py
- test/library/test_locally_biased_classical_shadows.py
- test/library/test_mutually_unbiased_bases_measurements.py
- test/library/test_randomized_projective_measurements.py
- test/post_processor/test_median_of_means.py
This de-duplicates some of the code logic in our unittests.
Closes #134
> De-duplicate some unittest logic

- releasenotes/config.yaml
Without this, the release notes are not being rendered correctly.
> docs: fix inclusion of release notes

- povm_toolbox/sampler/povm_sampler_job.py
This should ensure a more stable CI of the `coverage` job, unblocking the latest dependency updates and other PRs.
> fix: 100% coverage
